create extension if not exists pgcrypto;
create table if not exists organizations(id uuid primary key default gen_random_uuid(),clerk_org_id text not null unique,name text not null,created_at timestamptz not null default now());
create table if not exists monitors(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id) on delete cascade,name text not null,kind text not null check(kind in ('http','tcp','ssl')),target text not null,enabled boolean not null default true,interval_seconds integer not null default 60,failure_threshold integer not null default 2,recovery_threshold integer not null default 2,next_run_at timestamptz not null default now(),current_state text not null default 'healthy',failure_streak integer not null default 0,success_streak integer not null default 0,created_at timestamptz not null default now());
create table if not exists check_results(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id) on delete cascade,monitor_id uuid not null references monitors(id) on delete cascade,job_key text not null unique,ok boolean not null,status_code integer,latency_ms integer not null,failure_reason text,probe_region text not null,started_at timestamptz not null,completed_at timestamptz not null);
create table if not exists incidents(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id) on delete cascade,monitor_id uuid not null references monitors(id) on delete cascade,status text not null check(status in ('open','resolved')),title text not null,opened_at timestamptz not null default now(),resolved_at timestamptz);
create unique index if not exists one_open_incident_per_monitor on incidents(monitor_id) where status='open';
create table if not exists webhooks(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id) on delete cascade,url text not null,secret text not null,enabled boolean not null default true,created_at timestamptz not null default now());
create table if not exists outbox(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id) on delete cascade,event_type text not null,dedupe_key text not null unique,payload jsonb not null,sent_at timestamptz,created_at timestamptz not null default now());
create index if not exists monitors_due_idx on monitors(enabled,next_run_at);
