import net from 'node:net'
import tls from 'node:tls'
import { assertSafeHttpUrl, assertSafeHostname, parseTcpTarget, UnsafeTargetError } from '@/lib/security/ssrf'
import type { CheckResult, Monitor } from '@/lib/shared/types'
const timeoutMs=10000, maxBody=512000, maxRedirects=5
async function runHttp(m:Monitor){let url=await assertSafeHttpUrl(m.target);const started=Date.now();for(let i=0;i<=maxRedirects;i++){const r=await fetch(url,{redirect:'manual',signal:AbortSignal.timeout(timeoutMs),headers:{'user-agent':'HeartbeatMonitor/1.0'}});const loc=r.headers.get('location');if(r.status>=300&&r.status<400&&loc){if(i===maxRedirects)return{ok:false,statusCode:r.status,latencyMs:Date.now()-started,failureReason:'Too many redirects.'};url=await assertSafeHttpUrl(new URL(loc,url).toString());continue}let bodyBytes=0;if(r.body){const reader=r.body.getReader();while(true){const part=await reader.read();if(part.done)break;bodyBytes+=part.value.byteLength;if(bodyBytes>maxBody){await reader.cancel();return{ok:false,statusCode:r.status,latencyMs:Date.now()-started,failureReason:'Response body exceeded limit.'}}}}const ok=r.status>=200&&r.status<400;return{ok,statusCode:r.status,latencyMs:Date.now()-started,failureReason:ok?undefined:`HTTP ${r.status}`}}throw new Error('Redirect handling failed.')}
function runTcp(m:Monitor){const {hostname,port}=parseTcpTarget(m.target);const started=Date.now();return new Promise<{ok:boolean;latencyMs:number;failureReason?:string}>(resolve=>{void assertSafeHostname(hostname).then(()=>{const s=net.createConnection({host:hostname,port});let finished=false;const end=(x:{ok:boolean;latencyMs:number;failureReason?:string})=>{if(finished)return;finished=true;s.destroy();resolve(x)};s.setTimeout(timeoutMs);s.once('connect',()=>end({ok:true,latencyMs:Date.now()-started}));s.once('timeout',()=>end({ok:false,latencyMs:Date.now()-started,failureReason:'TCP timeout.'}));s.once('error',e=>end({ok:false,latencyMs:Date.now()-started,failureReason:e.message}))}).catch(e=>resolve({ok:false,latencyMs:Date.now()-started,failureReason:e instanceof Error?e.message:'Unsafe target.'}))})}
function runSsl(m:Monitor){const host=m.target.replace(/^https?:\/\//,'').split('/')[0].replace(/:\d+$/,'');const started=Date.now();return new Promise<{ok:boolean;latencyMs:number;failureReason?:string}>(resolve=>{void assertSafeHostname(host).then(()=>{const s=tls.connect({host,port:443,servername:host,rejectUnauthorized:false});let finished=false;const end=(x:{ok:boolean;latencyMs:number;failureReason?:string})=>{if(finished)return;finished=true;s.destroy();resolve(x)};s.setTimeout(timeoutMs);s.once('secureConnect',()=>{const c=s.getPeerCertificate();const valid=Boolean(c.subject&&c.valid_to&&Date.parse(c.valid_to)>Date.now()&&s.getProtocol());end({ok:valid,latencyMs:Date.now()-started,failureReason:valid?undefined:'Certificate invalid or expired.'})});s.once('timeout',()=>end({ok:false,latencyMs:Date.now()-started,failureReason:'TLS timeout.'}));s.once('error',e=>end({ok:false,latencyMs:Date.now()-started,failureReason:e.message}))}).catch(e=>resolve({ok:false,latencyMs:Date.now()-started,failureReason:e instanceof Error?e.message:'Unsafe target.'}))})}
export async function runMonitor(m:Monitor):Promise<CheckResult>{const started=new Date().toISOString(),jobKey=`${m.id}:${Date.now()}`;try{const result=m.kind==='http'?await runHttp(m):m.kind==='tcp'?await runTcp(m):await runSsl(m);return{id:crypto.randomUUID(),jobKey,monitorId:m.id,organizationId:m.organizationId,probeRegion:process.env.PROBE_REGION||'local',startedAt:started,completedAt:new Date().toISOString(),...result}}catch(e){return{id:crypto.randomUUID(),jobKey,monitorId:m.id,organizationId:m.organizationId,probeRegion:process.env.PROBE_REGION||'local',startedAt:started,completedAt:new Date().toISOString(),ok:false,latencyMs:Date.now()-Date.parse(started),failureReason:e instanceof UnsafeTargetError?e.message:e instanceof Error?e.message:'Check failed.'}}}
