import { isNeon, sql } from '@/lib/server/db'
import { transition } from '@/lib/domain/incident'
import type { CheckResult, Incident, Monitor, MonitorKind, WebhookEndpoint } from '@/lib/shared/types'
import { randomSecret } from '@/lib/security/signature'

type Mem={monitors:Monitor[];checks:CheckResult[];incidents:Incident[];webhooks:WebhookEndpoint[]}
const key='__heartbeat_final_mem__';const g=globalThis as typeof globalThis&{[key]?:Mem}
function memory(){if(!g[key]){const org=process.env.DEMO_ORGANIZATION_ID||'demo-org',now=new Date().toISOString();const make=(id:string,name:string,kind:MonitorKind,target:string,state:Monitor['currentState']='healthy'):Monitor=>({id,organizationId:org,name,kind,target,enabled:true,intervalSeconds:60,failureThreshold:2,recoveryThreshold:2,nextRunAt:now,currentState:state,failureStreak:state==='down'?2:0,successStreak:0,createdAt:now});g[key]={monitors:[make('home','Homepage','http','https://example.com'),make('health','Health API','http','https://example.com/health','down'),make('ssl','TLS certificate','ssl','example.com')],checks:[],incidents:[{id:'incident-health',organizationId:org,monitorId:'health',monitorName:'Health API',status:'open',title:'Health API is degraded',openedAt:now}],webhooks:[]} }return g[key]!}
export async function listMonitors(org:string):Promise<Monitor[]>{if(!isNeon){const db=memory();return db.monitors.filter(m=>m.organizationId===org).map(m=>({...m,lastCheck:db.checks.filter(c=>c.monitorId===m.id).at(-1)}))}const rows=await sql!`select m.*, (select row_to_json(c) from check_results c where c.monitor_id=m.id order by c.completed_at desc limit 1) as last_check from monitors m where m.organization_id=${org} order by m.created_at desc`;return rows.map((r:any)=>({...r,organizationId:r.organization_id,intervalSeconds:r.interval_seconds,failureThreshold:r.failure_threshold,recoveryThreshold:r.recovery_threshold,nextRunAt:new Date(r.next_run_at).toISOString(),currentState:r.current_state,failureStreak:r.failure_streak,successStreak:r.success_streak,createdAt:new Date(r.created_at).toISOString(),lastCheck:r.last_check||undefined}))}
export async function findMonitor(id:string,org:string){return (await listMonitors(org)).find(m=>m.id===id)}
export async function createMonitor(input:{organizationId:string;name:string;kind:MonitorKind;target:string}){if(!isNeon){const m:Monitor={id:crypto.randomUUID(),organizationId:input.organizationId,name:input.name,kind:input.kind,target:input.target,enabled:true,intervalSeconds:60,failureThreshold:2,recoveryThreshold:2,nextRunAt:new Date().toISOString(),currentState:'healthy',failureStreak:0,successStreak:0,createdAt:new Date().toISOString()};memory().monitors.push(m);return m}const rows=await sql!`insert into monitors(organization_id,name,kind,target) values(${input.organizationId},${input.name},${input.kind},${input.target}) returning *`;return rows[0] as Monitor}
export async function listIncidents(org:string):Promise<Incident[]>{if(!isNeon)return memory().incidents.filter(i=>i.organizationId===org).sort((a,b)=>b.openedAt.localeCompare(a.openedAt));const rows=await sql!`select i.*,m.name as monitor_name from incidents i join monitors m on m.id=i.monitor_id where i.organization_id=${org} order by i.opened_at desc`;return rows.map((r:any)=>({id:r.id,organizationId:r.organization_id,monitorId:r.monitor_id,monitorName:r.monitor_name,status:r.status,title:r.title,openedAt:new Date(r.opened_at).toISOString(),resolvedAt:r.resolved_at?new Date(r.resolved_at).toISOString():undefined}))}
export async function recordCheck(result:CheckResult){if(!isNeon){const db=memory();if(db.checks.some(c=>c.jobKey===result.jobKey))return{incidentAction:'none' as const};const m=db.monitors.find(x=>x.id===result.monitorId&&x.organizationId===result.organizationId);if(!m)throw new Error('Monitor not found.');db.checks.push(result);if(result.ok){m.successStreak++;m.failureStreak=0}else{m.failureStreak++;m.successStreak=0}const out=transition(m.currentState,result.ok,m.failureStreak,m.successStreak,m.failureThreshold,m.recoveryThreshold);m.currentState=out.nextState;m.nextRunAt=new Date(Date.now()+m.intervalSeconds*1000).toISOString();if(out.incidentAction==='open')db.incidents.push({id:crypto.randomUUID(),organizationId:m.organizationId,monitorId:m.id,monitorName:m.name,status:'open',title:`${m.name} is degraded`,openedAt:result.completedAt});if(out.incidentAction==='resolve'){const i=db.incidents.find(x=>x.monitorId===m.id&&x.status==='open');if(i){i.status='resolved';i.resolvedAt=result.completedAt}}return{incidentAction:out.incidentAction,monitor:m}}const rows=await sql!`insert into check_results(organization_id,monitor_id,job_key,ok,status_code,latency_ms,failure_reason,probe_region,started_at,completed_at) values(${result.organizationId},${result.monitorId},${result.jobKey},${result.ok},${result.statusCode||null},${result.latencyMs},${result.failureReason||null},${result.probeRegion},${result.startedAt},${result.completedAt}) on conflict(job_key) do nothing returning id`;if(!rows.length)return{incidentAction:'none' as const};const m=await findMonitor(result.monitorId,result.organizationId);if(!m)throw new Error('Monitor not found.');const failures=result.ok?0:m.failureStreak+1,successes=result.ok?m.successStreak+1:0;const out=transition(m.currentState,result.ok,failures,successes,m.failureThreshold,m.recoveryThreshold);await sql!`update monitors set current_state=${out.nextState},failure_streak=${failures},success_streak=${successes},next_run_at=now()+interval '60 seconds' where id=${m.id} and organization_id=${result.organizationId}`;if(out.incidentAction==='open')await sql!`insert into incidents(organization_id,monitor_id,status,title,opened_at) values(${m.organizationId},${m.id},'open',${m.name+' is degraded'},${result.completedAt}) on conflict do nothing`;if(out.incidentAction==='resolve')await sql!`update incidents set status='resolved',resolved_at=${result.completedAt} where monitor_id=${m.id} and status='open'`;return{incidentAction:out.incidentAction,monitor:m}}
export async function statusSnapshot(org:string){const [monitors,incidents]=await Promise.all([listMonitors(org),listIncidents(org)]);return{organizationId:org,overall:monitors.some(m=>m.currentState==='down')?'degraded':'operational',monitors,incidents,generatedAt:new Date().toISOString()}}
export async function createWebhook(org:string,url:string):Promise<WebhookEndpoint>{const endpoint={id:crypto.randomUUID(),organizationId:org,url,secret:randomSecret(),enabled:true,createdAt:new Date().toISOString()};if(!isNeon){memory().webhooks.push(endpoint);return endpoint}const rows=await sql!`insert into webhooks(id,organization_id,url,secret) values(${endpoint.id},${org},${url},${endpoint.secret}) returning id,organization_id,url,secret,enabled,created_at`;return{...endpoint,createdAt:new Date(rows[0].created_at).toISOString()}}
